name: LaTeX Build and Commit

on:
  push:
    paths:
      - '**.tex'     # Trigger only when .tex files are pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Install TeX Live
      - name: Install TeX Live
        run: |
          sudo apt-get update -y
          sudo apt-get install -y texlive-full

      # Step 3: Compile LaTeX Document
      - name: Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode main.tex  # Replace with your .tex filename
          # Add additional runs if needed (e.g., for references or index)

      # Step 4: Commit and Push the PDF back to the repository
      - name: Commit compiled PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add main.pdf  # Replace with your output PDF file
          git commit -m "Auto-compiled PDF on commit for main.tex"
          git push
